# Generated by Django 3.2.2 on 2021-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshared',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View'), ('COMMENT', 'Comment'), ('EDIT', 'Edit')], default='VIEW', max_length=50, verbose_name='Permission'),
        ),
    ]
